# Generated by Django 5.1.3 on 2024-11-29 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performanceCars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancecars',
            name='acceleration',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='performancecars',
            name='horsepower',
            field=models.FloatField(),
        ),
    ]
